server:
    port: 8090

cloud:
  eureka-host: localhost

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/auth_db
    username: noleg
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://${cloud.eureka-host}:8761/eureka


