server:
  port: 8090

cloud:
  eureka-host: localhost

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://0.0.0.0:5431/auth_db
    username: noleg
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: backend
            client-secret: mMneWtDPfthy2hx1iIN3SBIFQkZtAwT3
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: http://localhost:8100/realms/cbr-realm # добавить eureka

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://${cloud.eureka-host}:8761/eureka


