server:
  port: 8080

cloud:
  eureka-host: localhost
  processing-service-url: http://localhost:8081
  currency-rate-service-url: http://localhost:8082

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: currency-rate-service
              uri: ${cloud.currency-rate-service-url}
              predicates:
                - Path=/cbr/**
            - id: processing-service
              uri: ${cloud.processing-service-url}
              predicates:
                - Path=/processing/**

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://${cloud.eureka-host}:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

