server:
  port: 8081

spring:
  application:
    name: processing-service

  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/processing_db
    username: noleg
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

currency:
  service:
    url: http://localhost:8082/cbr

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://localhost:8761/eureka


