server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/processing_db
    username: noleg
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

currency:
  service:
    url: http://localhost:8082/cbr


